# Generated by Django 4.2.6 on 2023-11-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45, unique=True)),
                ('sobrenome', models.CharField(max_length=45)),
                ('endereco', models.CharField(max_length=255, unique=True)),
                ('telefone', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='username',
            new_name='user',
        ),
    ]
