# Generated by Django 4.2.6 on 2023-11-15 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_mecanico'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mecanico',
        ),
    ]
