# Generated by Django 4.2.6 on 2023-11-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_carro_equipe_alter_mecanico_equipe_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='pecas',
            field=models.ManyToManyField(to='app.peca'),
        ),
    ]
