# Generated by Django 4.2.6 on 2023-11-20 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_ordem_pecas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='defeito',
        ),
        migrations.DeleteModel(
            name='Ordem',
        ),
    ]
