# Generated by Django 4.2.6 on 2023-11-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_carro_defeito_delete_ordem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carro',
        ),
    ]
