# Generated by Django 4.2.6 on 2023-12-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='pecas',
            field=models.ManyToManyField(blank=True, to='app.peca'),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='servicos',
            field=models.ManyToManyField(blank=True, to='app.servico'),
        ),
    ]
