# Generated by Django 4.2.6 on 2023-12-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_ordem_pecas_alter_ordem_servicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='quantidadecomprada',
            field=models.IntegerField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
