# Generated by Django 4.2.6 on 2023-12-02 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_peca_quantidadecomprada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peca',
            name='quantidadecomprada',
        ),
    ]
