# Generated by Django 4.2.6 on 2023-12-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_ordem_debito'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='totalvenda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
